### ISSUE TITLE
SVL Download throws status 500 when there are no 3PP libraries

### ISSUE THREAD

**Issue by RavikiranCK** [janevegeorge/Open3PPManager#2]
When the project release has zero libraries, on clicking SVL Download throws status 500 Whitelabel Error Page.

StackTrace:
[java.lang.NullPointerException:]([url](url
![SVL_Download_Error](https://user-images.githubusercontent.com/7376081/85833946-29b3d580-b7b0-11ea-9db3-c761413809b7.PNG)
)) null
	at me.janeve.oss.o3ppm.svl.excel.SVLSheetBuilder.buildProjectReleaseSheet(SVLSheetBuilder.java:51) ~[classes/:na]
	at me.janeve.oss.o3ppm.svl.excel.ExcelSVLDownloadGenerator.generateSVL(ExcelSVLDownloadGenerator.java:42) ~[classes/:na]
	at me.janeve.oss.o3ppm.svl.BasicSVLDownloadGenerator.generateSVL(BasicSVLDownloadGenerator.java:49) ~[classes/:na]
	at me.janeve.oss.o3ppm.controllers.SVLDownloadController.downloadSVL(SVLDownloadController.java:41) ~[classes/:na]
	at me.janeve.oss.o3ppm.controllers.SVLDownloadController$$FastClassBySpringCGLIB$$eddb93d7.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]

**Comment by RavikiranCK** [comment]
Handled the null pointer exception in the class SVLSheetBuilder.  Added condition `releaseInformation.getDependencies() != null ` before the for loop.

Fix Branch: issues_2
Attached the downloaded file.
[SVL_Test_2.0..xlsx](https://github.com/janevegeorge/Open3PPManager/files/4835833/SVL_Test_2.0.xlsx)

**Comment by janevegeorge** [comment]
Verified in the fix and working.
